sudo: false
dist: bionic
language: ruby
services:
  - mysql
rvm:
  - 2.5.4
  - 2.6.3
  - truffleruby
before_install:
  - gem update --system
  - gem install bundle
script:
  - 'bin/rails db:environment:set RAILS_ENV=test'
  - 'bin/rails db:create RAILS_ENV=test'
  - 'bin/rails db:migrate RAILS_ENV=test'
  — 'bundle exec rspec'
cache: bundler
matrix:
  fast_finish: true
