sudo: false
dist: focal
language: ruby
services:
  - mysql
rvm:
  - 2.7.2
before_install:
  - gem update --system
  - gem install bundle
script:
  - "bin/rails db:create RAILS_ENV=test"
  - "bin/rails db:environment:set RAILS_ENV=test"
  - "bin/rails db:setup RAILS_ENV=test"
  - "bin/rails test"
cache: bundler
matrix:
  fast_finish: true
