sudo: false
dist: bionic
language: ruby
services:
  - mysql
rvm:
  - 2.5.4
  - 2.6.3
  - 2.7.0
before_install:
  - gem update --system
  - gem install bundle
script:
  - "bin/rails db:create RAILS_ENV=test"
  - "bin/rails db:environment:set RAILS_ENV=test"
  - "bin/rails db:setup RAILS_ENV=test"
  - "bin/rails test"
cache: bundler
matrix:
  fast_finish: true
