sudo: false
dist: bionic
language: ruby
services:
  - mysql
rvm:
  - 2.5.4
  - 2.6.3
  - truffleruby
before_install:
  - gem update --system
  - gem install bundler
cache: bundler
matrix:
  include:
     - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
