# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 077a4057ab8665b847c55e523ba9af6039751446ec18920cb0ad839a09596ea10f55b9fcf6ba227ac4e84ee1c31694e9f847f110d521a9c44ab76b430921c045

test:
  secret_key_base: 71e43e55eeb3b3d0af60d954b0b35fa82cada0e7500c5e877db9541a73b58305fe36458876ba371cdb35589970d18c1fe08e42cafb0d3292a038f616b50ca0c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
